Update ReadMe
team-telnyx/telnyx-webrtc-ios pull request #130
Opened 2024-08-29 14:42 UTC by isaacakakpo1

Readme Update

2024-08-30 08:06 UTC, RJSkorski requested changes

2024-08-30 08:06 UTC, RJSkorski commented on README.md
> +You can send debug stats for further investigation:
In case of any need to investigate any issue by Telnyx, please enable the debug stats that will be sent to Telnyx for analysis.

2024-08-30 08:06 UTC, RJSkorski commented on README.md
> +This sends debug stats to the telnyx backend. Note the **debug_stats_id** that would be use for investigation
Please store the **debug_stats_id** that would be used for investigation

2024-09-03 15:28 UTC, imranbilal1 approved these changes

2024-09-04 09:54 UTC, RJSkorski commented on README.md
> +Please store the **debug_stats_id that** would be used for investigation
the bold ends in wrong place

2024-09-04 10:35 UTC, RJSkorski approved these changes

2024-09-04 10:37 UTC, merged