[WEBRTC-2347] [feat] Stats
team-telnyx/telnyx-webrtc-ios pull request #145
Opened 2024-11-29 12:12 UTC by gbattistel

[[WEBRTC-2347] [feat] Stats](https://telnyx.atlassian.net/browse/WEBRTC-XXX)

2024-11-29 15:18 UTC, isaacakakpo1 approved these changes

2025-01-08 09:31 UTC, Oliver-Zimmerman requested changes
Minor comments. 

Will test when I have access to testflight

2025-01-08 09:31 UTC, Oliver-Zimmerman commented on TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift
> +    private let CANDIDATE_PAIR_LIMIT = 5
Do we need a limit? Also is this used?

2025-01-08 09:31 UTC, Oliver-Zimmerman commented on TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift
> +                if let outboundDict = outboundStat as? [String: NSObject], // Aseguramos el tipo
Let's leave public facing classes comments in English

2025-01-08 09:31 UTC, Oliver-Zimmerman commented on TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift
> +                    audioOutboundStats[index] = updatedStat as NSDictionary // Actualizamos en la lista
Same here

2025-01-08 12:23 UTC, gbattistel commented on TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift
> +    private let CANDIDATE_PAIR_LIMIT = 5
This was ported from the previous implementation of the WebRTC stats. I've removed because we are not using it.

2025-01-08 12:23 UTC, gbattistel commented on TelnyxRTC/Telnyx/WebRTC/Stats/WebRTCStatsReporter.swift
> +                    audioOutboundStats[index] = updatedStat as NSDictionary // Actualizamos en la lista
Done

2025-01-08 13:12 UTC, Oliver-Zimmerman approved these changes
Tested and was able to generate a json file that works as expected.

2025-01-09 13:58 UTC, merged