WEBRTC-620 - Disconnect client properly
team-telnyx/telnyx-webrtc-ios pull request #40
Opened 2021-07-07 22:47 UTC by guillermobattistel

[WebRTC-620 - Disconnect client properly](https://telnyx.atlassian.net/browse/WEBRTC-620)
---

- The socket was not been disconnecting when calling` socket.disconnect()`. We are adding a call to force the socket disconnection: `socket.forceDisconnect()`.
- We are also hanging up all the ongoing calls (if there's any call connected), and cleaning the list of available calls.
- On the Demo App we are setting the Call Screen states in the correct status after disconnecting the client or when an ongoing call has ended. 

## :older_man: :baby: Behaviors
### Before changes
- The calls remain active and the socket remained connected after calling the `disconnect() `function.

### After changes
- The client is disconnected properly when calling the `disconnect()` function and all the active calls are cancelled.
- The demo app updates the UI to the correct state after the call is disconnected.

## ✋ Manual testing

1. Go to the demo app. 
2. Connect using SIP credentials
3. Receive an incoming call
4. Accept the call
5. Press the disconnect button. 
6. The call should be cancelled and the Caller should receive the CALL ENDED event.

2021-07-08 06:49 UTC, j0nscalet commented on TelnyxRTC/Telnyx/Services/Socket.swift
> +        self.socket?.forceDisconnect()
Is there a reason why you're doing both a disconnect and a forceDisconnect here?

From the StarScream code it seems like a disconnect is a graceful way to disconnect while a forceDisconnect kills the transport.

2021-07-08 06:55 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +    func resetCallStates() {
I like the way you added this method to reset the call states on disconnect and the DONE call state. 👍

2021-07-08 07:06 UTC, j0nscalet requested changes
Overall looks good @guillermobattistel. See my comment about the disconnect/force disconnect - wondering what your thoughts are on that.

2021-07-08 07:06 UTC, j0nscalet commented on TelnyxRTC/Telnyx/Services/Socket.swift
> +        self.socket?.forceDisconnect()
Is there a reason why you're doing both a disconnect and a forceDisconnect here?

From the StarScream code it seems like a disconnect is a graceful way to disconnect while a forceDisconnect kills the transport.

2021-07-08 07:06 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +    func resetCallStates() {
I like the way you added this method to reset the call states on disconnect and the DONE call state. 👍

2021-07-08 08:57 UTC, j0nscalet commented on TelnyxRTC/Telnyx/Services/Socket.swift
> +        self.socket?.forceDisconnect()
Some context here...

```
public func stop(closeCode: UInt16 = CloseCode.normal.rawValue) {
        let capacity = MemoryLayout<UInt16>.size
        var pointer = [UInt8](repeating: 0, count: capacity)
        writeUint16(&pointer, offset: 0, value: closeCode)
        let payload = Data(bytes: pointer, count: MemoryLayout<UInt16>.size)
        write(data: payload, opcode: .connectionClose, completion: { [weak self] in
            self?.reset()
            self?.forceStop()
        })
    }
    
    public func forceStop() {
        transport.disconnect()
    }
```

So, ```socket.disconnect()``` invokes a ```stop``` with a normal close code and writes a message back on the socket. It's a graceful disconnect.

A ```socket.forceDisconnect()``` invokes a ```forceStop``` which just destroys the transport.

We'll probably want to do one or the other but not both, here.

2021-07-08 16:33 UTC, guillermobattistel commented on TelnyxRTC/Telnyx/Services/Socket.swift
> +        self.socket?.forceDisconnect()
The problem was that the socket.disconnect () was not terminating correctly because we were setting the parent object to null. The socket was definitely connected.
In the last commit I am setting the parent object to null after obtaining the callback that the socket was disconnected correctly and now the socket is been closed.

How I tested? 
1. Run the demo app and register with 2 iOS devices with the same credentials (device #1 and device #2). 
2. Disconnect from #1 .
3. Place a call from  client #3 to the user associated with the credentials of step 1  (it could be from the web-dialer). Device #2 should start ringing.
4. Reject the call from device #2. The client #3 will still calling. For the backend, the device #1 still connected.

After my changes on step 4, as soon as the device #2 rejects the call, the client #3 will receive the CALL ENDED event.

2021-07-12 12:48 UTC, j0nscalet approved these changes

2021-07-12 13:11 UTC, merged