WEBRTC-628 - Add Token login screen on Demo App
team-telnyx/telnyx-webrtc-ios pull request #43
Opened 2021-07-13 16:37 UTC by guillermobattistel

[WebRTC-628 - Add Token login screen on Demo App](https://telnyx.atlassian.net/browse/WEBRTC-628)
---

A login switch selector has been added to the Settings screen. 
User can select to login using SIP credentials (user and password) or using a Telnyx token.

</br>
</br>
<table>
  <tr>
    <td>Login with Token</td>
     <td>Login with SIP Credentials</td>
  </tr>
  <tr>
<td><img width="270" alt="Screen Shot 2021-07-13 at 13 33 29" src="https://user-images.githubusercontent.com/75636882/125490835-4b7da445-18e0-4c4c-bb24-a734b854b062.png"></td>
<td><img width="270" alt="Screen Shot 2021-07-13 at 13 33 09" src="https://user-images.githubusercontent.com/75636882/125490887-2f86675c-373a-43d8-b265-ba3019db0455.png"></td>
  </tr>
 </table>

## :older_man: :baby: Behaviors
### Before changes
Login with token was not supported on the demo app.

### After changes
User can select between login in with SIP credentials or Telnyx token.

## ✋ Manual testing

1. Go to the demo app. 
2. Change the login selector to "On"
3. UI will be updated to enter the token instead of the SIP credentials.
4. Enter a valid token: https://developers.telnyx.com/docs/v2/webrtc/quickstart
5. Press the connect button.
6. Place a call.

2021-07-15 03:45 UTC, j0nscalet requested changes
Good job, just some small changes that I think will improve understandability for developers. :)

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/Views/UISettingsView.swift
> +    public func isTokenLoginSelected() -> Bool {
This should be a property and not a method.
```
public var isTokenSelected {
    get { return self.loginSelector.isOn }
}
```

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +                guard let telnyxToken = self.settingsView.tokenLabel.text, !telnyxToken.isEmpty else { return }
If you're going to validate the token to ensure it's not empty you should let the user know when it's invalid instead of just returning early. 

I think it's best to add some field validation at least log it (like you do for the call button below). I know it's a demo app so it's not that important but I think the little things add up to a better developer experience.

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +            if self.settingsView.isTokenLoginSelected() {
This should be a property not a method (see my comments in UISettingsView).

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +                guard let sipUser = self.settingsView.sipUsernameLabel.text, !sipUser.isEmpty,
Say idea here - when the fields are invalid you should let the user know.

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +                guard let txConfig = txConfig else { return }
I don't think this guard is necessary because txConfig should be set in either of the two previous blocks.

Even if it was you could handle that inside the `client.connect` method and throw an error then handle it like you're already doing.

2021-07-15 03:45 UTC, j0nscalet commented on TelnyxWebRTCDemo/ViewController.swift
> +                let userDefaults = UserDefaults.init()
We should clean up the way that we're initializing UserDefaults since you're initializing it twice: once here and the other on line 83. You could add this as a field and use the initializer to initialize it or in ViewDidLoad.

```
var userDefaults: UserDefaults

onViewDidLoad(){
    self.userDefaults = UserDefaults.init()
}

83: let deviceToken = self.userDefaults.getPushToken()

112: self.userDefaults.saveUser(sipUser: sipUser, password: password)
```

2021-07-15 19:21 UTC, guillermobattistel commented on TelnyxWebRTCDemo/ViewController.swift
> +                let userDefaults = UserDefaults.init()
Good idea!

2021-07-15 19:21 UTC, guillermobattistel commented on TelnyxWebRTCDemo/ViewController.swift
> +                guard let txConfig = txConfig else { return }
good catch!

2021-07-15 19:21 UTC, guillermobattistel commented on TelnyxWebRTCDemo/Views/UISettingsView.swift
> +    public func isTokenLoginSelected() -> Bool {
Good idea. Done.

2021-07-15 19:22 UTC, guillermobattistel commented on TelnyxWebRTCDemo/ViewController.swift
> +                guard let sipUser = self.settingsView.sipUsernameLabel.text, !sipUser.isEmpty,
Done.

2021-07-16 07:43 UTC, j0nscalet approved these changes
👍  :)

2021-07-27 18:17 UTC, merged